name: dragmesh
channels:
  - defaults
  - nvidia
  - pytorch
dependencies:
  - blas=1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.1.0
  - cuda-version=12.9
  - expat=2.7.1
  - filelock=3.17.0
  - freetype=2.13.3
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9f
  - khronos-opencl-icd-loader=2024.05.08
  - lcms2=2.16
  - lerc=3.0
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - libpng=1.6.39
  - libtiff=4.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - networkx=3.4.2
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pillow=11.1.0
  - pip=25.2
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.18
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.5
  - sqlite=3.50.2
  - sympy=1.14.0
  - tbb=2021.8.0
  - tk=8.6.15
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.5
      - bleach==6.2.0
      - blinker==1.9.0
      - ccimport==0.4.4
      - chardet==5.2.0
      - click==8.2.1
      - colorama==0.4.6
      - colorlog==6.10.1
      - comm==0.2.3
      - configargparse==1.7.1
      - cumm-cu118==0.7.11
      - cycler==0.12.1
      - dash==3.2.0
      - dataclasses-json==0.6.7
      - debugpy==1.8.16
      - decorator==4.4.2
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - diff-gaussian-rasterization==0.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - ffmpeg==1.4
      - fire==0.7.1
      - flask==3.1.2
      - fonttools==4.59.2
      - fqdn==1.5.1
      - freetype-py==2.5.1
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gputil==1.4.0
      - grpcio==1.74.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - imageio==2.34.1
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - iopath==0.1.10
      - ipykernel==6.30.1
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - lark==1.2.2
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - lmdb==1.7.5
      - loguru==0.7.3
      - lpips==0.1.4
      - lxml==6.0.1
      - manifold3d==3.3.2
      - mapbox-earcut==2.0.0
      - markdown==3.9
      - markdown-it-py==4.0.0
      - marshmallow==3.26.1
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.4
      - moviepy==1.0.3
      - msgspec==0.20.0
      - multidict==6.6.4
      - mypy-extensions==1.1.0
      - narwhals==2.5.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.13.0
      - nodeenv==1.9.1
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - objaverse==0.1.7
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.2
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pccm==0.4.16
      - piq==0.8.0
      - platformdirs==4.4.0
      - plotly==6.3.0
      - plyfile==1.0.3
      - pointnet2==0.0.0
      - portalocker==3.2.0
      - proglog==0.1.12
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==6.32.1
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pybind11==3.0.1
      - pycollada==0.9.2
      - pyglet==1.5.31
      - pygltflib==1.16.5
      - pygments==2.19.2
      - pyopengl==3.1.0
      - pyopengl-accelerate==3.1.10
      - pyparsing==3.2.4
      - pyperclip==1.11.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.1
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytorch-lightning==2.4.0
      - pytorch3d==0.7.8
      - pytransform3d==3.14.2
      - pytz==2025.2
      - pywin32==311
      - pywinpty==3.0.0
      - pyzmq==27.1.0
      - referencing==0.36.2
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.27.1
      - rtree==1.4.1
      - sapien==3.0.1
      - scikit-image==0.22.0
      - scikit-learn==1.5.0
      - scipy==1.10.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - setuptools==80.9.0
      - shapely==2.1.2
      - simple-knn==0.0.0
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - spconv-cu118==2.3.8
      - stack-data==0.6.3
      - svg-path==7.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - terminado==0.18.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tinycss2==1.4.0
      - tinycudann==2.0
      - tomli==2.2.1
      - torchaudio==2.4.1
      - torchmetrics==1.8.2
      - torchvision==0.19.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transforms3d==0.4.2
      - trimesh==4.5.1
      - types-python-dateutil==2.9.0.20250822
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - vhacdx==0.0.10
      - viser==1.0.16
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - win32-setctime==1.2.0
      - wrapt==2.0.1
      - xatlas==0.0.11
      - xxhash==3.6.0
      - yarl==1.20.1
      - yourdfpy==0.0.58
      - zipp==3.23.0

